name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -v -o output/

    - name: Test
      run: go test -v ./...

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: output/*

    - name: Set Tag
      id: tag
      run: echo "TAG=go_prometheus_proxmox_integration-$(date +'%Y%m%d')" >> $GITHUB_ENV

    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.PAT }}
        tag: ${{ env.TAG }}
        artifacts: "output/*"
