name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - uses: actions/checkout@v3
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        github_token: ${{ secrets.PAT }}
        tag: "release"
        artifacts: "release.tar.gz,foo/*.txt"
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
